Add  missing movies
RickDB/PlexAniSync-Custom-Mappings pull request #36
Opened 2022-09-03 19:57 UTC by Arial-Z

Add :
- Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train
- Kabaneri of the Iron Fortress: The Battle of Unato
- Made in Abyss: Journey's Dawn
- Made in Abyss: Wandering Twilight
- Made in Abyss: Dawn of the Deep Soul
- My Hero Academia : Two Heroes
- My Hero Academia : Heroes Rising
- The Garden of Sinners (as separate movies)
- The Irregular at Magic High School: The Girl Who Summons the Stars
- Sword Art Online: The Movie – Ordinal Scale

2022-09-14 17:23 UTC, reconman commented
You were still waiting for review, right? Was pretty busy the last few weeks so I forgot.

2022-09-15 06:43 UTC, Arial-Z commented
yeah, but that okay take your time :)

2022-09-15 06:45 UTC, Arial-Z commented
Added
- "Gintama: The Movie"
- "Gintama: The Movie: The Final Chapter: Be Forever Yorozuya"
- Added MAL synonym for "KonoSuba: God's Blessing on this Wonderful World! Legend of Crimson"

2022-09-18 16:08 UTC, reconman requested changes
Some incorrect titles with extra spaces.

2022-09-18 16:08 UTC, reconman commented on movies-tmdb.en.yaml
> +  - title: "Love, Chunibyo & Other Delusions ! -Take On Me"
```suggestion
  - title: "Love, Chunibyo & Other Delusions! -Take On Me"
```

2022-09-18 16:08 UTC, reconman commented on movies-tmdb.en.yaml
> +  - title: "My Hero Academia : Two Heroes"
```suggestion
  - title: "My Hero Academia: Two Heroes"
```

2022-09-18 16:08 UTC, reconman commented on movies-tmdb.en.yaml
> +  - title: "My Hero Academia : Heroes Rising"
```suggestion
  - title: "My Hero Academia: Heroes Rising"
```

2022-09-18 16:09 UTC, reconman commented
Most of your mappings problably work out-of-the box using PlexAniSync's search function, but I'll add them anyways just in case.

2022-09-19 07:05 UTC, Arial-Z commented
Done and thank you

2022-09-20 17:29 UTC, reconman approved these changes

2022-09-20 17:31 UTC, merged