The Misfit of Demon King Academy S2 & fix D.Gray-man S2
RickDB/PlexAniSync-Custom-Mappings pull request #43
Opened 2023-01-18 08:17 UTC by Arial-Z

Add The Misfit of Demon King Academy S2 cour 1 and 2
Correct D.Gray-man S2 start episode following change on Space brother.
I'm not sur if i'm using the correct number as you put -50 for S2 of Space brother (S1 have 51 ep and S2 48), i'm a little lost.
D.Gray-man S1 have 51ep and S2 52ep so i set start at -52 (51 of the first season +1)

2023-01-23 08:41 UTC, Arial-Z commented
Also add Slam Dunk

2023-01-23 14:13 UTC, Arial-Z commented
Fixed start numbers follow discord guidelines and added BOFURI

2023-01-23 19:37 UTC, reconman requested changes

2023-01-23 19:37 UTC, reconman commented on series-tvdb.en.yaml
> +        start: -25
Forgot that we have a feature to combine multiple seasons into one automatically. See One Piece in this mapping file.

Omitting the `start` for every season should have the same result as the current mapping.

Can you test it?

Same is true for Space Brothers and D.Gray-Man.

2023-01-24 11:02 UTC, Arial-Z commented
going to test it on my custom mappings file with slam dunk as i'm currently watching it

2023-01-24 22:30 UTC, reconman approved these changes

2023-01-24 22:30 UTC, merged