Adds missing shows and some german synonyms
RickDB/PlexAniSync-Custom-Mappings pull request #46
Opened 2023-03-22 12:32 UTC by InteractiveNinja

Added shows:
* My Next Life as a Villainess [S1](https://anilist.co/anime/104647/Otome-Game-no-Hametsu-Flag-shika-Nai-Akuyaku-Reijou-ni-Tensei-shiteshimatta/) [S2](https://anilist.co/anime/120209/Otome-Game-no-Hametsu-Flag-shika-Nai-Akuyaku-Reijou-ni-Tensei-shiteshimatta-X/)
* Anti-Magic Academy: The 35th Test Platoon [S1](https://anilist.co/anime/20704/Taimadou-Gakuen-35-Shiken-Shoutai/)
* Arifureta: From Commonplace to World's Strongest [S1](https://anilist.co/anime/100668/Arifureta-Shokugyou-de-Sekai-Saikyou/) [S2](https://anilist.co/anime/112323/Arifureta-Shokugyou-de-Sekai-Saikyou-2nd-season/)
* Summer Time Rendering [S1](https://anilist.co/anime/129201/Summer-Time-Render/)
* Suppose a Kid from the Last Dungeon Boonies moved to a starter town? [S1](https://anilist.co/anime/112649/Tatoeba-Last-Dungeon-Mae-no-Mura-no-Shounen-ga-Joban-no-Machi-de-Kurasu-Youna-Monogatari/)
* GRANBLUE FANTASY The Animation [S1](https://anilist.co/anime/21361/GRANBLUE-FANTASY-The-Animation/) [S2](https://anilist.co/anime/107346/GRANBLUE-FANTASY-The-Animation-Season-2/)
* The Strongest Sage with the Weakest Crest [S1](https://anilist.co/anime/129191/Shikkakumon-no-Saikyou-Kenja/)

Added Synoyms per Show:
**Is It Wrong to Try to Pick Up Girls in a Dungeon?**
* Danmachi: Is It Wrong to Try to Pick Up Girls in a Dungeon?
* Danmachi

**The Slime Diaries: That Time I Got Reincarnated as a Slime**
* Die Schleim-Tagebücher (German Title)

**That Time I Got Reincarnated as a Slime**
* Meine Wiedergeburt als Schleim in einer anderen Welt (German Title)

**Chaika the Coffin Princess**
* Chaika - Die Sargprinzessin (German Title)

2023-03-22 12:36 UTC, InteractiveNinja commented
> @reconman just saw the commit from my last PR [af9a242](https://github.com/RickDB/PlexAniSync-Custom-Mappings/commit/af9a242997a3bc75ce3a7ef81c1ea3866d6d99f4) Is there an order that should be followed?

nvm just saw its alphabetically..

2023-03-26 13:05 UTC, reconman requested changes

2023-03-26 13:05 UTC, reconman commented on series-tvdb.en.yaml
> +  - title: "Arifureta Shokugyou de Sekai Saikyou"
English titles as main, Japanese as synonym

2023-03-26 13:05 UTC, reconman commented on series-tvdb.en.yaml
> +  - title: "Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta…"
Same

2023-03-26 13:05 UTC, reconman commented on series-tvdb.en.yaml
> +  - title: "Shikkakumon no Saikyou Kenja"
Same

2023-03-26 13:05 UTC, reconman commented on series-tvdb.en.yaml
> +        anilist-id: 129191
Missing empty line

2023-03-26 13:05 UTC, reconman commented on series-tvdb.en.yaml
> +  - title: "Taimadou Gakuen 35 Shiken Shoutai"
Same

2023-03-26 13:05 UTC, reconman commented on series-tvdb.en.yaml
> +  - title: "Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari"
Same

2023-03-26 14:29 UTC, reconman commented
Closed via 77803b332b2d64829a33446ad6e81f7101846fc6

2023-03-26 14:29 UTC, closed without merging